# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

location_search <- function(num_times, num_subjects, W_total) {
    .Call(`_spaco_location_search`, num_times, num_subjects, W_total)
}

V_projection <- function(K, num_times, num_subjects, X, V0) {
    .Call(`_spaco_V_projection`, K, num_times, num_subjects, X, V0)
}

empirical_W_total <- function(num_times, num_subjects, K, OBS, Y) {
    .Call(`_spaco_empirical_W_total`, num_times, num_subjects, K, OBS, Y)
}

pairs_count <- function(num_times, num_subjects, W_total) {
    .Call(`_spaco_pairs_count`, num_times, num_subjects, W_total)
}

ridge_penalized <- function(num_subjects, num_times, num_features, K, XI, OI, V0Phi0, eps) {
    .Call(`_spaco_ridge_penalized`, num_subjects, num_times, num_features, K, XI, OI, V0Phi0, eps)
}

rearrange_G <- function(K, Utmp, U0, G) {
    .Call(`_spaco_rearrange_G`, K, Utmp, U0, G)
}

kronecker_VPhi <- function(K, V0, Phi0, V, Phi, VPhi, U2, U3) {
    .Call(`_spaco_kronecker_VPhi`, K, V0, Phi0, V, Phi, VPhi, U2, U3)
}

rescale_VPhi <- function(K, Phi_norm, V_norm, V, Phi, VPhi) {
    .Call(`_spaco_rescale_VPhi`, K, Phi_norm, V_norm, V, Phi, VPhi)
}

rescale_U <- function(num_subjects, num_times, num_features, K, XI, OI, VPhi, eps) {
    .Call(`_spaco_rescale_U`, num_subjects, num_times, num_features, K, XI, OI, VPhi, eps)
}

sigma_init <- function(homoNoise, num_features, Osum, xhat, XI, index) {
    .Call(`_spaco_sigma_init`, homoNoise, num_features, Osum, xhat, XI, index)
}

posterior_kronecker_VPhi <- function(K, V, Phi, VPhi) {
    .Call(`_spaco_posterior_kronecker_VPhi`, K, V, Phi, VPhi)
}

sigma_transform <- function(num_times, num_features, sigma, s) {
    .Call(`_spaco_sigma_transform`, num_times, num_features, sigma, s)
}

posterior_distribution <- function(num_subjects, num_times, num_features, K, fit_intercept, intercepts, XI, OI, VPhi, s, sigmaF, Z, beta) {
    .Call(`_spaco_posterior_distribution`, num_subjects, num_times, num_features, K, fit_intercept, intercepts, XI, OI, VPhi, s, sigmaF, Z, beta)
}

kronecker_Vmu <- function(K, num_subjects, num_features, V, mu, A0) {
    .Call(`_spaco_kronecker_Vmu`, K, num_subjects, num_features, V, mu, A0)
}

s2_transform <- function(num_subjects, num_features, sigma, s2) {
    .Call(`_spaco_s2_transform`, num_subjects, num_features, sigma, s2)
}

Mt_creator <- function(num_subjects, num_times, num_features, K, s2, sigma, XT, OT, A0, V, cov, OBS) {
    .Call(`_spaco_Mt_creator`, num_subjects, num_times, num_features, K, s2, sigma, XT, OT, A0, V, cov, OBS)
}

penalty_search <- function(num_times, nlambda1, max_iter0, lambda1s, A, Omega, dfs) {
    .Call(`_spaco_penalty_search`, num_times, nlambda1, max_iter0, lambda1s, A, Omega, dfs)
}

Omega_errors <- function(num_times, nlambda1, ridge_traj, a, b, lambda1s, phi, Omega, errors) {
    .Call(`_spaco_Omega_errors`, num_times, nlambda1, ridge_traj, a, b, lambda1s, phi, Omega, errors)
}

Omega_update <- function(num_times, nlambda1, lambda1_dfmin, lambda1_dfmax, ridge_traj, lam1criterion, a, b, Omega) {
    .Call(`_spaco_Omega_update`, num_times, nlambda1, lambda1_dfmin, lambda1_dfmax, ridge_traj, lam1criterion, a, b, Omega)
}

binary_search <- function(num, norm_constraint, a, b) {
    .Call(`_spaco_binary_search`, num, norm_constraint, a, b)
}

phi_transform <- function(num_times, lambda1, ridge_traj, h, a, b, Omega) {
    .Call(`_spaco_phi_transform`, num_times, lambda1, ridge_traj, h, a, b, Omega)
}

Phi_solver <- function(K, num_times, nlambda1, lambda1_dfmin, lambda1_dfmax, ridge_traj, lam1criterion, self_h, update_smooth_penalty, lambda1, self_Phi, h, Omega, M) {
    .Call(`_spaco_Phi_solver`, K, num_times, nlambda1, lambda1_dfmin, lambda1_dfmax, ridge_traj, lam1criterion, self_h, update_smooth_penalty, lambda1, self_Phi, h, Omega, M)
}

kronecker_Phimu <- function(K, num_subjects, num_times, Phi, mu, A0) {
    .Call(`_spaco_kronecker_Phimu`, K, num_subjects, num_times, Phi, mu, A0)
}

Mj_creator <- function(num_subjects, num_times, num_features, K, sigma, XJ, OJ, A0, Phi, cov, OBS) {
    .Call(`_spaco_Mj_creator`, num_subjects, num_times, num_features, K, sigma, XJ, OJ, A0, Phi, cov, OBS)
}

V_solver <- function(K, num_features, self_V, h, M) {
    .Call(`_spaco_V_solver`, K, num_features, self_V, h, M)
}

muZ_transform <- function(dimZ1, k, selfK, mutrans, Ztrans, vec, Z0, tmp1, mat) {
    .Call(`_spaco_muZ_transform`, dimZ1, k, selfK, mutrans, Ztrans, vec, Z0, tmp1, mat)
}

kronecker_muPhi <- function(K, num_subjects, num_times, Phi, mu, A0) {
    .Call(`_spaco_kronecker_muPhi`, K, num_subjects, num_times, Phi, mu, A0)
}

sigma_helper <- function(num_subjects, num_times, K, idx1length, idx1, A0, A1, cov, O1, Phi) {
    .Call(`_spaco_sigma_helper`, num_subjects, num_times, K, idx1length, idx1, A0, A1, cov, O1, Phi)
}

sigma_solver <- function(num_subjects, num_times, num_features, idxlength, XJ, A0, A1, V, idx) {
    .Call(`_spaco_sigma_solver`, num_subjects, num_times, num_features, idxlength, XJ, A0, A1, V, idx)
}

sigmaF_helper <- function(num_subjects, K, fit_intercept, intercepts, Z, beta) {
    .Call(`_spaco_sigmaF_helper`, num_subjects, K, fit_intercept, intercepts, Z, beta)
}

sigmaF_solver <- function(num_subjects, K, fit, mu, cov) {
    .Call(`_spaco_sigmaF_solver`, num_subjects, K, fit, mu, cov)
}

left_creator <- function(h, T1, left) {
    .Call(`_spaco_left_creator`, h, T1, left)
}

ts_creator <- function(num_subjects, num_times, T1, O1) {
    .Call(`_spaco_ts_creator`, num_subjects, num_times, T1, O1)
}

mean_curve_update <- function(num_subjects, num_times, num_features, lam, Psi, O1, Omega, X) {
    .Call(`_spaco_mean_curve_update`, num_subjects, num_times, num_features, lam, Psi, O1, Omega, X)
}

cv_creator <- function(nlam, num_subjects, num_times, num_features, lams, s0, O1, Psi, Omega, X, cv) {
    .Call(`_spaco_cv_creator`, nlam, num_subjects, num_times, num_features, lams, s0, O1, Psi, Omega, X, cv)
}

R_creator <- function(num_subjects, num_times, num_features, basis, B0, R) {
    .Call(`_spaco_R_creator`, num_subjects, num_times, num_features, basis, B0, R)
}

